language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: LNnbl8czTdN9QzfA8CZena8fsCYMmmNj3/YbQGyN+/87yiEqqCzgTrJPCNFCENoEpXTB5KvyTd497faP3r+tJeWrxwGODkZ/7S7V+PTyTjce7Tdhk0D5I37JlApXoCWUjc5ZuS0XsvxuushsLEkKFTUFLoQPYbP7vASW+pLDJtIJkOrsf/EIdA8HHTmQVgfFpBHfjLHClJfbwpSYI1XzSZxt9L7P/8XOzp88Ue91Zkk+muCcB700/lheCf0iHl6c6dnxZdR2s0NMES4gQGJOBGEqTlKu8rv/yVmiOCNO3nU2nONy4aR8EQ2jf0h9o2ru3eanAhSKa0LfxXdnOnswlEsPxaMbJYkDNBfvSu/3Bur7YKVlWr7Hwp+XXTd160PuXWswDTiCN6IbXBcTRl/1a2xARaGhy514i01xzq3qd9qYXfp7Ysh7CaYX1G3BIOF1ETt+EmvdWzRqgG2MWQrhrfLlGf/AUoJfb+8XI3+Z7n0sQV6xLsKUGiLTxdKqeChwTvafK9WhSUV+ei+ulnJmw7vY5rf1jf6yj/zeKHVzyugpg1fhgP3P24t008qQpCtWNbf6AkhszDKdaDfylUGMBb3Cxl6elo4RRMbsPp+I+dMBBbhb+ZeWQ5d+VM9kzjcSW11N8dS7to2fp/7vySLIvzZ9KhHWTljdbElI+B+ydes=
  app: next-offer-server
  on:
    repo: tspeaks/next-offer-server
